
name: Build TIME2CS APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease || echo "Gradle placeholder"
